name: virgil_e3kit
description: Virgil e3kit implementation
version: 0.0.3
homepage: https://virgilsecurity.com
repository: https://github.com/tealblue-team/virgil-e3kit-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.virgilsecurity.virgil_e3kit
        pluginClass: VirgilE3kitPlugin
      ios:
        pluginClass: VirgilE3kitPlugin